### ISSUE TITLE
missing icons & duplicate snippet

### ISSUE THREAD

**Issue by nerdull** [SchottkySpectroscopyIMP/data-acquisition#1]
@NanaVan in your `daq.py` file:
 - icons are all missing, namely lines 318-321
 - _personal suggestion_: use relative path to specify the icons
 - lines 863-871 seem to be duplicate with lines 650-658?

**Comment by NanaVan** [comment]
@nerdull  Thanks~
* the icons' path is changed into `/data-acquisition/icons/icon.png`
* the lines 863-871 is deleted.

**Comment by nerdull** [comment]
@NanaVan I've corrected the path to `./icons/icon.png`.
